import type { Metadata } from "next";
import { Urbanist, Epilogue } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const urbanist = Urbanist({
  subsets: ["latin"],
  variable: "--heading",
});

const epilogue = Epilogue({
  subsets: ["latin"],
  variable: "--sans",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${urbanist.variable} ${epilogue.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
